name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and package application
      run: |
        TAG_NAME="${{ github.ref_name }}"
        TARGET_VERSION="${TAG_NAME#v}"
        ./build.sh "$TARGET_VERSION" /tmp/out

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VmChamp-linux-${{ github.ref_name }}-amd64
        path: /tmp/out/VmChamp-linux-${{ github.ref_name }}-amd64
        retention-days: 1

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: /tmp/out/VmChamp-linux-${{ github.ref_name }}-amd64
        body: |
          ${{ github.event.head_commit.message }}
